### ISSUE TITLE
BMP2Tile 0.5 "Unsupported bitmap format Format32bppArgb"...

### ISSUE THREAD

**Issue by sverx** [maxim-zhao/bmp2tile#14]
... but source PNG image is 16 color indexed, using 3 colors only, and I can convert it with no problem using BMP2Tile 0.44 (well, palette is kind of weird there, it is `.db $00 $00 $00 $00 $00 $3F $3F $3F $3F $3F $03`)

here's the image (a single 8x8 tile)
![sprite](https://user-images.githubusercontent.com/6738932/68429875-dbad7b80-01a6-11ea-9f52-af08a02765a1.png)

**Comment by maxim-zhao** [comment]
Something about the .net image loader makes it convert this image to true-colour. I think it is because it is technically a 2bpp image and tools generally don;t do a great job supporting that.

**Comment by sverx** [comment]
@fdwr: the input image should not have any alpha channel (in my image, it hadn't)

**Comment by maxim-zhao** [comment]
Hmm, unfortunately it's just .net's default image loader which I guess goes 32bpp when it sees alpha. Maybe I can get another image library...
