### ISSUE TITLE
BMP2TileGUI.exe exports a SMS (6-bit RGB) palette even when GG (12-bit RGB) is selected

### ISSUE THREAD

**Issue by ArmandCCode** [maxim-zhao/bmp2tile#24]
How to reproduce the issue:
* Open a valid input image in BMP2TileGUI.exe
* Go to the "Palette" tab
* Select "GG (12-bit RGB)"
* Notice that the text output is a 12-bit RGB palette
* Click "Save" and save the palette as an inc file

Open the inc file and notice that the output is a 6-bit RGB palette.
This palette is sadly unusable for Game Gear homebrew.

Notes:
* Also affects palettes saved as raw bin files. 
* This issue is **not** present in the command line version. Where adding the parameter -ggpalette successfully outputs a file that can be loaded as-is on Game Gear.

**Comment by maxim-zhao** [comment]
Fixed in version 0.61, thanks for the bug report!
