### ISSUE TITLE
... a checkbox to keep 4bpp images palette untouched

### ISSUE THREAD

**Issue by sverx** [maxim-zhao/bmp2tile#7]
As the title said, a checkbox that makes a 4bpp palette stay as it is, even if unused colors are present in the image, would be very handy.
I guess adding another 'if' after
`if tilesColumn.PixelFormat=pf4bit then`
which simply does
`h=15`
if the said checkbox is checked should be everything needed.
Thanks!

**Comment by maxim-zhao** [comment]
I had a quick go and I end up getting what looks like uninitialised memory in the upper bytes, which seems counterproductive. This is using [GetPaletteEntries](https://msdn.microsoft.com/en-us/library/dd144907(v=vs.85).aspx) to do the grunt work, so maybe that is producing undefined results for unused items or maybe it's the PNG decoder lib I'm using.

**Comment by maxim-zhao** [comment]
Fixed in v0.42.
