### ISSUE TITLE
width and height swapped when calling the CompressTilemap plug-in function

### ISSUE THREAD

**Issue by sverx** [maxim-zhao/bmp2tile#8]
I'm working on the plug-in for the updated STMcompr format (that would just be the same with a 1-byte header containing the width of the tilemap) and I spent a few minutes wondering why I couldn't get the correct width of the tilemap in my STM compressor plugin.
Here's why: https://github.com/maxim-zhao/bmp2tile/blob/48299c5cf578b7f7c2ffe975cad29c41ebbd63b3/source/Unit1.pas#L685
now I'm wondering if you're going to fix it or should I use height instead? (I bet the other compressors doesn't use this anyway so you won't break them, right?)

**Comment by maxim-zhao** [comment]
Most probably multiply them to compute the buffer size. I ought to fix it though, it is silly - but it means everyone will need to update BMP2Tile.

**Comment by sverx** [comment]
I would say no one will really rush to update, unless they need to compress tilemaps in STM's new format.
Which means I'll wait for your new release, then release the new plugin with the requirement for BMP2Tile new version.
(The alternative would be to release the plugin as it is now, workaround included, but then it will just silently start creating broken output files with your next releases... and I don't like that very much)
Let me know your plans.

**Comment by maxim-zhao** [comment]
Plan:

1. Fix it today
2. Release

**Comment by maxim-zhao** [comment]
Try 0.43...

**Comment by sverx** [comment]
Looks like the exe in the zip isn't updated :|

**Comment by maxim-zhao** [comment]
Whoops. Try it now.

**Comment by sverx** [comment]
Now it's perfect, thanks! (but you missed a release and skipped a version in readme file's history section...)

**Comment by maxim-zhao** [comment]
...fixed :)
