### ISSUE TITLE
Support for up to 32 simultaneous colors

### ISSUE THREAD

**Issue by sdsnatcher** [maxim-zhao/bmp2tile#9]
The Sega Master System supports up to 32 simultaneous colors for the background, but bmp2tile currently artificially restricts it to only 16.

It would be nice to have support for 32 simultaneous colors.

**Comment by maxim-zhao** [comment]
Selecting two palettes and assigning one per tile is a much more tricky problem than bmp2tile solves right now. It could try to detect if the image is already suitably divided into 8x8 blocks of matching palettes, I suppose.

**Comment by sverx** [comment]
> Selecting two palettes and assigning one per tile is a much more tricky problem than bmp2tile solves right now. It could try to detect if the image is already suitably divided into 8x8 blocks of matching palettes, I suppose.

This would be very handy. I suppose while loading the image it could detect that and ask the user if he wants to continue in dual-palette mode, where tiles would work as expected, tilemaps would use the palette bit according to image and palettes would export a 'dual palette' (32 bytes for SMS).

**Comment by maxim-zhao** [comment]
Fixed in 710664d8815e45f8e2b385f4dd8d028c2f9bfa30. It does the palette fixing for you but it does do it silently.
